// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWcStZuAXnA6i5Z2deRkuAzOWaBSw5JA',
    appId: '1:598013182728:web:2697e384f40ffd674ce2bd',
    messagingSenderId: '598013182728',
    projectId: 'hackathon-8b5a1',
    authDomain: 'hackathon-8b5a1.firebaseapp.com',
    storageBucket: 'hackathon-8b5a1.appspot.com',
    measurementId: 'G-3KEXVVXCXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJkM9oL6pkwoY8b216yzWYAkyMwAtXk8',
    appId: '1:598013182728:android:8bb3b1c7acccf9d34ce2bd',
    messagingSenderId: '598013182728',
    projectId: 'hackathon-8b5a1',
    storageBucket: 'hackathon-8b5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt6Lt4ppdMPV_6b4mK560571X1OrDTa7A',
    appId: '1:598013182728:ios:45ce1691d5069e684ce2bd',
    messagingSenderId: '598013182728',
    projectId: 'hackathon-8b5a1',
    storageBucket: 'hackathon-8b5a1.appspot.com',
    iosBundleId: 'com.example.tourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt6Lt4ppdMPV_6b4mK560571X1OrDTa7A',
    appId: '1:598013182728:ios:a54d57d8ba90b5244ce2bd',
    messagingSenderId: '598013182728',
    projectId: 'hackathon-8b5a1',
    storageBucket: 'hackathon-8b5a1.appspot.com',
    iosBundleId: 'com.example.tourism.RunnerTests',
  );
}
